apiVersion: v1
kind: Service
metadata:
  name: example-argocd-server
  namespace: default
  labels:
    app.kubernetes.io/name: example-argocd-server
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: argocd
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: example-argocd-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8080
      nodePort: 30443
      protocol: TCP

